function [fitresult, gof] = createFit(acceleration, velocity, torque)
%CREATEFIT(ACCELERATION,VELOCITY,TORQUE)
%  Create a fit.
%
%  Data for 'Fit Transparency Planes' fit:
%      X Input : acceleration
%      Y Input : velocity
%      Z Output: torque
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Dec-2021 21:24:13


%% Fit: 'Fit Transparency Planes'.
[xData, yData, zData] = prepareSurfaceData( acceleration, velocity, torque );

% Set up fittype and options.
ft = fittype( 'poly11' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );



